# -*- coding: utf-8 -*-
"""Sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FLKUNjhSkctlF35h2gYklxnYwHSQu6kG
"""

# CÉLULA 1 — INSTALAÇÃO DE DEPENDÊNCIAS
# Execute primeiro

!pip -q install pandas numpy matplotlib seaborn wordcloud scikit-learn nltk spacy transformers datasets accelerate sentencepiece
!python -m spacy download en_core_web_sm

# CÉLULA 2 — IMPORTS

import os
import re
import gc
import json
import math
import random
import zipfile
import warnings
from io import BytesIO
from collections import Counter, defaultdict

import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from wordcloud import WordCloud

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    confusion_matrix,
    classification_report,
    roc_auc_score
)
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.neural_network import MLPClassifier

import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

import spacy
import torch

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    TrainingArguments,
    Trainer,
    pipeline
)

warnings.filterwarnings("ignore")

nltk.download("stopwords")
nltk.download("punkt")

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

print("GPU disponível:", torch.cuda.is_available())

# CÉLULA 3 — CONFIG

CONFIG = {
    # Amostragem / viabilidade no Colab
    "MAX_SAMPLES": 50000,          # reduza para 5000 se quiser velocidade
    "MIN_TEXT_LEN": 20,
    "MIN_PRODUCT_COUNT": 100,
    "TOP_N_PRODUCTS": 10,

    # Split
    "TEST_SIZE": 0.15,
    "VAL_SIZE": 0.15,              # fração sobre o dataset total
    "RANDOM_STATE": 42,

    # Pré-processamento
    "USE_STEMMING_IF_SPACY_FAILS": True,
    "MAX_TEXT_CHARS_FOR_LABELING": 512,
    "MAX_TEXT_CHARS_FOR_MODEL_INPUT": 512,

    # Pseudo-rotulagem
    "PSEUDO_LABEL_MODEL": "distilbert-base-uncased-finetuned-sst-2-english",
    "PSEUDO_LABEL_MIN_CONFIDENCE": 0.80,

    # Deep Learning
    "TRY_DISTILBERT": True,
    "DISTILBERT_MODEL_NAME": "distilbert-base-uncased",
    "TRAIN_EPOCHS": 2,
    "TRAIN_BATCH_SIZE": 8,
    "EVAL_BATCH_SIZE": 8,
    "LEARNING_RATE": 2e-5,
    "WEIGHT_DECAY": 0.01,
    "MAX_TOKEN_LENGTH": 256,

    # Fallback
    "TFIDF_MAX_FEATURES": 12000,
    "MLP_HIDDEN": (256, 64),
    "MLP_MAX_ITER": 20,

    # Saída
    "OUTPUT_ROOT": "/content/outputs",
}

for subdir in ["metrics", "figures", "tables", "models"]:
    os.makedirs(os.path.join(CONFIG["OUTPUT_ROOT"], subdir), exist_ok=True)

print(json.dumps(CONFIG, indent=2))

# CÉLULA 4 — GOOGLE DRIVE (OPCIONAL)
# Execute apenas se quiser salvar no Drive

# from google.colab import drive
# drive.mount('/content/drive')

# Exemplo opcional:
# CONFIG["OUTPUT_ROOT"] = "/content/drive/MyDrive/cfpb_outputs"
# for subdir in ["metrics", "figures", "tables", "models"]:
#     os.makedirs(os.path.join(CONFIG["OUTPUT_ROOT"], subdir), exist_ok=True)

# CÉLULA 5 — FUNÇÕES DE CARGA DE DADOS

def load_data():
    cols = [
    "Product",
    "Issue",
    "Sub-issue",
    "Consumer complaint narrative",
    "Date received"
    ]

    chunks = []
    for chunk in pd.read_csv("/content/drive/MyDrive/complaints.csv", usecols=cols, chunksize=200_000):
        chunk = chunk[chunk["Consumer complaint narrative"].notna()]
        chunk = chunk[chunk["Consumer complaint narrative"].str.len() > 20]
        chunks.append(chunk)

    df = pd.concat(chunks, ignore_index=True)
    return df

df_raw = load_data()
df_raw.head(3)

# CÉLULA 6 — INSPEÇÃO E NORMALIZAÇÃO DE COLUNAS

def normalize_columns(df):
    df = df.copy()
    df.columns = [c.strip() for c in df.columns]
    return df

df_raw = normalize_columns(df_raw)

expected_cols = [
    "Product",
    "Issue",
    "Sub-issue",
    "Consumer complaint narrative",
    "Date received"
]

existing_cols = [c for c in expected_cols if c in df_raw.columns]
missing_cols = [c for c in expected_cols if c not in df_raw.columns]

print("Colunas presentes:")
print(existing_cols)
print("\nColunas ausentes:")
print(missing_cols)

# CÉLULA 7 — FILTRAGEM INICIAL E AMOSTRAGEM

def choose_text_column(df):
    preferred = "Consumer complaint narrative"
    if preferred in df.columns:
        return preferred

    candidates = [c for c in df.columns if "narrative" in c.lower() or "complaint" in c.lower()]
    if candidates:
        return candidates[0]

    obj_cols = df.select_dtypes(include="object").columns.tolist()
    if obj_cols:
        return obj_cols[0]

    raise ValueError("Nenhuma coluna textual adequada encontrada.")

TEXT_COL = choose_text_column(df_raw)
PRODUCT_COL = "Product" if "Product" in df_raw.columns else None

print("Coluna de texto escolhida:", TEXT_COL)
print("Coluna de produto:", PRODUCT_COL)

df = df_raw.copy()

df[TEXT_COL] = df[TEXT_COL].fillna("").astype(str)
df = df[df[TEXT_COL].str.len() >= CONFIG["MIN_TEXT_LEN"]].copy()

if PRODUCT_COL is not None:
    product_counts = df[PRODUCT_COL].value_counts(dropna=False)
    valid_products = product_counts[product_counts >= CONFIG["MIN_PRODUCT_COUNT"]].index.tolist()
    df = df[df[PRODUCT_COL].isin(valid_products)].copy()

    top_products = (
        df[PRODUCT_COL]
        .value_counts()
        .head(CONFIG["TOP_N_PRODUCTS"])
        .index
        .tolist()
    )
    df = df[df[PRODUCT_COL].isin(top_products)].copy()

if len(df) > CONFIG["MAX_SAMPLES"]:
    df = df.sample(CONFIG["MAX_SAMPLES"], random_state=CONFIG["RANDOM_STATE"]).copy()

df = df.reset_index(drop=True)

print("Shape após filtros:", df.shape)
if PRODUCT_COL is not None:
    print("\nProdutos incluídos:")
    print(df[PRODUCT_COL].value_counts().head(15))

# CÉLULA 8 — PRÉ-PROCESSAMENTO DE TEXTO

STOPWORDS_EN = set(stopwords.words("english"))

try:
    NLP = spacy.load("en_core_web_sm", disable=["parser", "ner"])
    SPACY_OK = True
except Exception:
    NLP = None
    SPACY_OK = False

stemmer = PorterStemmer()

def basic_clean(text: str) -> str:
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", " ", text)
    text = re.sub(r"[^a-z\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

def lemmatize_with_spacy(text: str) -> str:
    doc = NLP(text)
    tokens = [
        token.lemma_.strip()
        for token in doc
        if token.lemma_.strip()
        and token.lemma_.strip() not in STOPWORDS_EN
        and len(token.lemma_.strip()) > 1
    ]
    return " ".join(tokens)

def stem_with_nltk(text: str) -> str:
    tokens = text.split()
    tokens = [t for t in tokens if t not in STOPWORDS_EN and len(t) > 1]
    tokens = [stemmer.stem(t) for t in tokens]
    return " ".join(tokens)

def preprocess_text(text: str) -> str:
    text = basic_clean(text)
    if not text:
        return ""

    if SPACY_OK:
        try:
            return lemmatize_with_spacy(text)
        except Exception:
            pass

    if CONFIG["USE_STEMMING_IF_SPACY_FAILS"]:
        return stem_with_nltk(text)

    tokens = [t for t in text.split() if t not in STOPWORDS_EN and len(t) > 1]
    return " ".join(tokens)

print("spaCy disponível:", SPACY_OK)

df["processed_text"] = df[TEXT_COL].apply(preprocess_text)
df = df[df["processed_text"].str.len() > 0].reset_index(drop=True)

print("Shape após pré-processamento:", df.shape)
df[[TEXT_COL, "processed_text"]].head(3)

# CÉLULA 9 — PSEUDO-ROTULAGEM DE SENTIMENTO
# Observação metodológica:
# A base do CFPB não traz rótulo nativo de sentimento.
# Portanto, usamos weak supervision / pseudo-labeling com um modelo pré-treinado.
# Neutros/baixa confiança são descartados para tornar o problema binário mais limpo.

device = 0 if torch.cuda.is_available() else -1

sentiment_pipe = pipeline(
    "sentiment-analysis",
    model=CONFIG["PSEUDO_LABEL_MODEL"],
    tokenizer=CONFIG["PSEUDO_LABEL_MODEL"],
    device=device
)

def chunk_iterable(lst, batch_size):
    for i in range(0, len(lst), batch_size):
        yield lst[i:i+batch_size]

def pseudo_label_texts(texts, batch_size=32, min_conf=0.80):
    labels = []
    scores = []

    for batch in chunk_iterable(texts, batch_size):
        short_batch = [t[:CONFIG["MAX_TEXT_CHARS_FOR_LABELING"]] for t in batch]
        preds = sentiment_pipe(short_batch, truncation=True)

        for p in preds:
            label_raw = p["label"].upper()
            score = float(p["score"])

            if score < min_conf:
                labels.append(None)
                scores.append(score)
                continue

            if "POS" in label_raw:
                labels.append(1)
            elif "NEG" in label_raw:
                labels.append(0)
            else:
                labels.append(None)

            scores.append(score)

    return labels, scores

df["pseudo_label"], df["pseudo_score"] = pseudo_label_texts(
    df["processed_text"].tolist(),
    batch_size=32,
    min_conf=CONFIG["PSEUDO_LABEL_MIN_CONFIDENCE"]
)

before = len(df)
df = df.dropna(subset=["pseudo_label"]).copy()
df["pseudo_label"] = df["pseudo_label"].astype(int)
df = df.reset_index(drop=True)
after = len(df)

print(f"Amostras antes da pseudo-rotulagem filtrada: {before}")
print(f"Amostras após descarte de baixa confiança/neutros: {after}")
print("\nDistribuição de rótulos:")
print(df["pseudo_label"].value_counts(normalize=False))
print(df["pseudo_label"].value_counts(normalize=True))

# CÉLULA 10 — SPLIT ESTRATIFICADO
# Mantemos as colunas originais para poder fazer análise temática apenas no teste previsto como negativo.

target_col = "pseudo_label"

train_df, temp_df = train_test_split(
    df,
    test_size=(CONFIG["TEST_SIZE"] + CONFIG["VAL_SIZE"]),
    stratify=df[target_col],
    random_state=CONFIG["RANDOM_STATE"]
)

relative_test = CONFIG["TEST_SIZE"] / (CONFIG["TEST_SIZE"] + CONFIG["VAL_SIZE"])

val_df, test_df = train_test_split(
    temp_df,
    test_size=relative_test,
    stratify=temp_df[target_col],
    random_state=CONFIG["RANDOM_STATE"]
)

train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

print("Train:", train_df.shape)
print("Val:", val_df.shape)
print("Test:", test_df.shape)

for name, part in [("train", train_df), ("val", val_df), ("test", test_df)]:
    print(f"\nDistribuição em {name}:")
    print(part[target_col].value_counts(normalize=True))

# CÉLULA 11 — TREINO: DISTILBERT OU FALLBACK MLP + TF-IDF

class TextDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=256):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            str(self.texts[idx]),
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt"
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = torch.tensor(int(self.labels[idx]), dtype=torch.long)
        return item

def compute_metrics_for_trainer(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average="binary", zero_division=0
    )
    acc = accuracy_score(labels, preds)

    try:
        probs = torch.softmax(torch.tensor(logits), dim=1)[:, 1].numpy()
        roc_auc = roc_auc_score(labels, probs)
    except Exception:
        roc_auc = np.nan

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "roc_auc": roc_auc
    }

model_type_used = None
final_model = None
tokenizer_or_vectorizer = None
trainer = None

X_train = train_df["processed_text"].tolist()
y_train = train_df[target_col].tolist()

X_val = val_df["processed_text"].tolist()
y_val = val_df[target_col].tolist()

X_test = test_df["processed_text"].tolist()
y_test = test_df[target_col].tolist()

if CONFIG["TRY_DISTILBERT"]:
    try:
        print("Tentando fine-tuning com DistilBERT...")

        bert_tokenizer = DistilBertTokenizerFast.from_pretrained(CONFIG["DISTILBERT_MODEL_NAME"])
        bert_model = DistilBertForSequenceClassification.from_pretrained(
            CONFIG["DISTILBERT_MODEL_NAME"],
            num_labels=2
        )

        train_dataset = TextDataset(X_train, y_train, bert_tokenizer, CONFIG["MAX_TOKEN_LENGTH"])
        val_dataset = TextDataset(X_val, y_val, bert_tokenizer, CONFIG["MAX_TOKEN_LENGTH"])

        training_args = TrainingArguments(
            output_dir=os.path.join(CONFIG["OUTPUT_ROOT"], "models", "distilbert_runs"),
            num_train_epochs=CONFIG["TRAIN_EPOCHS"],
            per_device_train_batch_size=CONFIG["TRAIN_BATCH_SIZE"],
            per_device_eval_batch_size=CONFIG["EVAL_BATCH_SIZE"],
            learning_rate=CONFIG["LEARNING_RATE"],
            weight_decay=CONFIG["WEIGHT_DECAY"],
            eval_strategy="epoch",
            save_strategy="epoch",
            logging_strategy="epoch",
            load_best_model_at_end=True,
            metric_for_best_model="f1",
            greater_is_better=True,
            report_to="none",
            fp16=torch.cuda.is_available()
        )

        trainer = Trainer(
            model=bert_model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=val_dataset,
            compute_metrics=compute_metrics_for_trainer
        )

        trainer.train()

        final_model = trainer.model
        tokenizer_or_vectorizer = bert_tokenizer
        model_type_used = "distilbert"

        save_dir = os.path.join(CONFIG["OUTPUT_ROOT"], "models", "distilbert_final")
        final_model.save_pretrained(save_dir)
        tokenizer_or_vectorizer.save_pretrained(save_dir)

        print("DistilBERT treinado com sucesso.")

    except Exception as e:
        print("Falha no DistilBERT. Motivo:", str(e))
        model_type_used = None

        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

if model_type_used is None:
    print("Usando fallback: TF-IDF + MLPClassifier")

    tfidf = TfidfVectorizer(
        max_features=CONFIG["TFIDF_MAX_FEATURES"],
        ngram_range=(1, 2),
        min_df=3,
        max_df=0.95
    )

    X_train_vec = tfidf.fit_transform(X_train)
    X_val_vec = tfidf.transform(X_val)
    X_test_vec = tfidf.transform(X_test)

    mlp = MLPClassifier(
        hidden_layer_sizes=CONFIG["MLP_HIDDEN"],
        max_iter=CONFIG["MLP_MAX_ITER"],
        random_state=CONFIG["RANDOM_STATE"],
        early_stopping=True,
        validation_fraction=0.1
    )

    mlp.fit(X_train_vec, y_train)

    final_model = mlp
    tokenizer_or_vectorizer = tfidf
    model_type_used = "mlp_tfidf"

    import joblib
    joblib.dump(
        final_model,
        os.path.join(CONFIG["OUTPUT_ROOT"], "models", "mlp_model.joblib")
    )
    joblib.dump(
        tokenizer_or_vectorizer,
        os.path.join(CONFIG["OUTPUT_ROOT"], "models", "tfidf_vectorizer.joblib")
    )

print("Modelo final:", model_type_used)

# CÉLULA 12 — AVALIAÇÃO NO CONJUNTO DE TESTE

def evaluate_distilbert(model, tokenizer, texts, y_true):
    # Clear GPU cache before evaluation to maximize available memory
    import gc
    import torch
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    model.eval()

    all_logits = []

    # Process texts in smaller batches during evaluation to prevent OOM
    # Reuse chunk_iterable function from CÉLULA 9
    batch_size = CONFIG["EVAL_BATCH_SIZE"]
    if batch_size == 0:
        batch_size = 1 # Ensure batch size is at least 1

    for batch_texts in chunk_iterable(texts, batch_size):
        enc = tokenizer(
            batch_texts,
            truncation=True,
            padding="max_length",
            max_length=CONFIG["MAX_TOKEN_LENGTH"],
            return_tensors="pt"
        )
        enc = {k: v.to(device) for k, v in enc.items()}

        with torch.no_grad():
            outputs = model(**enc)
            all_logits.append(outputs.logits.detach().cpu()) # Move logits to CPU to free GPU memory

    logits = torch.cat(all_logits, dim=0) # Concatenate all logits after processing all batches

    probs = torch.softmax(logits, dim=1)[:, 1].numpy()
    preds = np.argmax(logits.numpy(), axis=1)

    return preds, probs

def evaluate_mlp(model, vectorizer, texts, y_true):
    X_vec = vectorizer.transform(texts)
    preds = model.predict(X_vec)
    probs = model.predict_proba(X_vec)[:, 1]
    return preds, probs

if model_type_used == "distilbert":
    y_pred, y_prob = evaluate_distilbert(final_model, tokenizer_or_vectorizer, X_test, y_test)
else:
    y_pred, y_prob = evaluate_mlp(final_model, tokenizer_or_vectorizer, X_test, y_test)

acc = accuracy_score(y_test, y_pred)
precision, recall, f1, _ = precision_recall_fscore_support(
    y_test, y_pred, average="binary", zero_division=0
)
roc_auc = roc_auc_score(y_test, y_prob)
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred, zero_division=0)

metrics_dict = {
    "model": model_type_used,
    "n_train": len(train_df),
    "n_val": len(val_df),
    "n_test": len(test_df),
    "accuracy": acc,
    "precision": precision,
    "recall": recall,
    "f1": f1,
    "roc_auc": roc_auc
}

print(json.dumps(metrics_dict, indent=2))
print("\nClassification report:\n")
print(report)

metrics_path = os.path.join(CONFIG["OUTPUT_ROOT"], "metrics", "test_metrics.json")
with open(metrics_path, "w", encoding="utf-8") as f:
    json.dump(metrics_dict, f, ensure_ascii=False, indent=2)

report_path = os.path.join(CONFIG["OUTPUT_ROOT"], "metrics", "classification_report.txt")
with open(report_path, "w", encoding="utf-8") as f:
    f.write(report)

cm_df = pd.DataFrame(cm, index=["Real Neg", "Real Pos"], columns=["Pred Neg", "Pred Pos"])
cm_df.to_csv(os.path.join(CONFIG["OUTPUT_ROOT"], "metrics", "confusion_matrix.csv"))

plt.figure(figsize=(6, 4))
sns.heatmap(cm_df, annot=True, fmt="d", cmap="Blues")
plt.title("Matriz de Confusão — Teste")
plt.tight_layout()
plt.savefig(os.path.join(CONFIG["OUTPUT_ROOT"], "figures", "confusion_matrix.png"), dpi=200)
plt.show()

# CÉLULA 13 — CONSOLIDAÇÃO DO TESTE COM PREDIÇÕES
# A análise de dores deve usar apenas as reclamações negativas previstas pelo modelo final.

test_results = test_df.copy()
test_results["pred_sentiment"] = y_pred
test_results["pred_prob_positive"] = y_prob
test_results["pred_label_name"] = test_results["pred_sentiment"].map({0: "negative", 1: "positive"})

test_results.to_csv(
    os.path.join(CONFIG["OUTPUT_ROOT"], "tables", "test_predictions.csv"),
    index=False
)

negative_test = test_results[test_results["pred_sentiment"] == 0].copy().reset_index(drop=True)

print("Total no teste:", len(test_results))
print("Negativas previstas no teste:", len(negative_test))
negative_test.head(3)

# CÉLULA 14 — DICIONÁRIO DE TEMAS DE INSATISFAÇÃO

THEME_RULES = {
    "cobranca_indevida": [
        "unauthorized charge", "wrong charge", "charged", "billing error",
        "double charge", "incorrect fee", "unexpected fee"
    ],
    "falha_no_atendimento": [
        "customer service", "representative", "agent", "no response",
        "rude", "hang up", "poor service", "did not help"
    ],
    "estorno_reembolso": [
        "refund", "reimbursement", "chargeback", "money back", "reversed transaction"
    ],
    "fraude": [
        "fraud", "scam", "fraudulent", "unauthorized transaction", "account takeover"
    ],
    "taxas_juros": [
        "interest rate", "apr", "fee", "fees", "late fee", "overdraft fee"
    ],
    "problemas_pagamento": [
        "payment not posted", "payment issue", "payment processing",
        "autopay", "late payment", "payment reversal"
    ],
    "erro_info_credito": [
        "credit report", "incorrect information", "inaccurate", "wrong balance",
        "wrong account", "reporting error"
    ],
    "encerramento_conta": [
        "account closed", "closed my account", "account closure", "terminated account"
    ],
    "cobranca_divida": [
        "debt collection", "collector", "collection agency", "harassment", "collecting debt"
    ],
    "roubo_identidade": [
        "identity theft", "stolen identity", "identity was used", "someone opened"
    ]
}

def assign_themes(text):
    text_l = text.lower()
    matched = []
    for theme, patterns in THEME_RULES.items():
        for p in patterns:
            if p in text_l:
                matched.append(theme)
                break
    if not matched:
        matched.append("outros")
    return matched

negative_test["themes"] = negative_test[TEXT_COL].fillna("").astype(str).apply(assign_themes)
negative_test[["themes"]].head(5)

# CÉLULA 15 — EXPANSÃO DOS TEMAS E TABELAS POR PRODUTO

def explode_themes(df_neg, product_col="Product"):
    rows = []
    for _, row in df_neg.iterrows():
        prod = row[product_col] if product_col in df_neg.columns else "sem_produto"
        for theme in row["themes"]:
            rows.append({
                "product": prod,
                "theme": theme,
                "complaint_id": row["Complaint ID"] if "Complaint ID" in row.index else None
            })
    return pd.DataFrame(rows)

theme_long = explode_themes(negative_test, PRODUCT_COL if PRODUCT_COL else "product_placeholder")

theme_counts = (
    theme_long
    .groupby(["product", "theme"])
    .size()
    .reset_index(name="count")
    .sort_values(["product", "count"], ascending=[True, False])
)

theme_counts.to_csv(
    os.path.join(CONFIG["OUTPUT_ROOT"], "tables", "themes_by_product.csv"),
    index=False
)

theme_counts.head(20)

# CÉLULA 16 — TOP TERMOS POR PRODUTO (NEGATIVAS)
# Vamos gerar também frequência de termos e n-grams por categoria.

def get_top_terms(texts, ngram_range=(1,1), top_n=20):
    texts = [t for t in texts if isinstance(t, str) and t.strip()]
    if not texts:
        return pd.DataFrame(columns=["term", "count"])

    vec = CountVectorizer(
        stop_words=list(STOPWORDS_EN) + ["xxxx", "xx"], # Adicionando 'xxxx' e 'xx' às stopwords
        ngram_range=ngram_range,
        min_df=2
    )
    X = vec.fit_transform(texts)
    freqs = np.asarray(X.sum(axis=0)).ravel()
    terms = np.array(vec.get_feature_names_out())

    order = np.argsort(freqs)[::-1]
    top_terms = pd.DataFrame({
        "term": terms[order][:top_n],
        "count": freqs[order][:top_n]
    })
    return top_terms

all_top_tables = []

if PRODUCT_COL is not None:
    for product, grp in negative_test.groupby(PRODUCT_COL):
        uni_df = get_top_terms(grp["processed_text"].tolist(), ngram_range=(1,1), top_n=20)
        uni_df["product"] = product
        uni_df["type"] = "unigram"

        bi_df = get_top_terms(grp["processed_text"].tolist(), ngram_range=(2,2), top_n=20)
        bi_df["product"] = product
        bi_df["type"] = "bigram"

        all_top_tables.append(uni_df)
        all_top_tables.append(bi_df)

top_terms_df = pd.concat(all_top_tables, ignore_index=True) if all_top_tables else pd.DataFrame()
top_terms_df.to_csv(
    os.path.join(CONFIG["OUTPUT_ROOT"], "tables", "top_terms_by_product.csv"),
    index=False
)

top_terms_df.head(20)

# CÉLULA 17 — WORD CLOUDS POR PRODUTO

def safe_filename(text):
    return re.sub(r"[^a-zA-Z0-9_\-]+", "_", str(text))

if PRODUCT_COL is not None:
    for product, grp in negative_test.groupby(PRODUCT_COL):
        corpus = " ".join(grp["processed_text"].dropna().astype(str).tolist()).strip()
        if not corpus:
            continue

        wc = WordCloud(
            width=600,
            height=300,
            background_color="white",
            stopwords=list(STOPWORDS_EN) + ["xxxx", "xx"], # Adicionando 'xxxx' e 'xx' às stopwords,
            collocations=False
        ).generate(corpus)

        plt.figure(figsize=(12, 6))
        plt.imshow(wc, interpolation="bilinear")
        plt.axis("off")
        plt.title(f"Nuvem de palavras — {product}")
        plt.tight_layout()
        save_path = os.path.join(
            CONFIG["OUTPUT_ROOT"], "figures", f"wordcloud_{safe_filename(product)}.png"
        )
        plt.savefig(save_path, dpi=200)
        plt.show()

"""### CÉLULA EXTRA — NOVAS WORD CLOUDS BASEADAS NOS TOP TERMOS FILTRADOS"""

def safe_filename(text):
    return re.sub(r"[^a-zA-Z0-9_\-]+|\[|\]", "_", str(text)) # Added \[ and \] to remove list brackets if they appear

if PRODUCT_COL is not None:
    print("Gerando Word Clouds a partir dos Top Termos por Produto...")
    for product in top_terms_df["product"].unique():
        product_terms = top_terms_df[top_terms_df["product"] == product]

        # Create a frequency dictionary from the filtered top terms
        # WordCloud can take a dictionary where keys are words and values are frequencies
        frequencies = dict(zip(product_terms["term"], product_terms["count"]))

        if not frequencies:
            print(f"Nenhum termo encontrado para {product}. Pulando Word Cloud.")
            continue

        wc = WordCloud(
            width=600,
            height=300,
            background_color="white",
            collocations=False, # We're providing pre-aggregated terms, so no need for internal collocation detection
            normalize_plurals=True # Helps combine singular and plural forms
        ).generate_from_frequencies(frequencies)

        plt.figure(figsize=(12, 6))
        plt.imshow(wc, interpolation="bilinear")
        plt.axis("off")
        plt.title(f"Nuvem de palavras (Top Termos) — {product}")
        plt.tight_layout()
        save_path = os.path.join(
            CONFIG["OUTPUT_ROOT"], "figures", f"wordcloud_top_terms_{safe_filename(product)}.png"
        )
        plt.savefig(save_path, dpi=200)
        plt.show()
    print("Word Clouds geradas e salvas na pasta figures.")
else:
    print("Não há coluna de produto para gerar Word Clouds por produto a partir dos top termos.")

# CÉLULA 18 — GRÁFICOS DE FREQUÊNCIA POR PRODUTO

if PRODUCT_COL is not None:
    for product, grp in negative_test.groupby(PRODUCT_COL):
        top_uni = get_top_terms(grp["processed_text"].tolist(), ngram_range=(1,1), top_n=15)
        if top_uni.empty:
            continue

        plt.figure(figsize=(10, 6))
        sns.barplot(data=top_uni, x="count", y="term", palette="Reds_r")
        plt.title(f"Top termos negativos — {product}")
        plt.xlabel("Frequência")
        plt.ylabel("Termo")
        plt.tight_layout()

        save_path = os.path.join(
            CONFIG["OUTPUT_ROOT"], "figures", f"freq_terms_{safe_filename(product)}.png"
        )
        plt.savefig(save_path, dpi=200)
        plt.show()

# CÉLULA 19 — RESUMO EXECUTIVO AUTOMÁTICO

def top_theme_summary(theme_counts_df):
    if theme_counts_df.empty:
        return {}

    summary = {}
    for product, grp in theme_counts_df.groupby("product"):
        top_grp = grp.sort_values("count", ascending=False).head(5)
        summary[product] = list(zip(top_grp["theme"], top_grp["count"]))
    return summary

summary_themes = top_theme_summary(theme_counts)

label_dist = df["pseudo_label"].value_counts().to_dict()

print("\n## RESUMO EXECUTIVO\n")
print(f"- Tamanho da base utilizada após filtros e pseudo-rotulagem: **{len(df)}**")
print(f"- Train / Val / Test: **{len(train_df)} / {len(val_df)} / {len(test_df)}**")
print(f"- Distribuição dos rótulos pseudo-supervisionados: **{label_dist}**")
print(f"- Melhor modelo efetivamente usado: **{model_type_used}**")
print(f"- Accuracy: **{acc:.4f}**")
print(f"- Precision: **{precision:.4f}**")
print(f"- Recall: **{recall:.4f}**")
print(f"- F1-score: **{f1:.4f}**")
print(f"- ROC-AUC: **{roc_auc:.4f}**")
print(f"- Reclamações negativas previstas no teste: **{len(negative_test)}**")

print("\n## Temas mais recorrentes por produto\n")
for product, items in summary_themes.items():
    print(f"### {product}")
    for theme, count in items:
        print(f"- {theme}: {count}")
    print()

# CÉLULA 20 — LISTAGEM DOS ARTEFATOS GERADOS

for root, dirs, files in os.walk(CONFIG["OUTPUT_ROOT"]):
    level = root.replace(CONFIG["OUTPUT_ROOT"], "").count(os.sep)
    indent = " " * 2 * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = " " * 2 * (level + 1)
    for f in files:
        print(f"{subindent}{f}")

